export const address = [
  { street: '43 Katie Hill', city: 'Van Nuys', state: 'CA', zip: '91406' },
  { street: '84694 Arizona Drive', city: 'Boulder', state: 'CO', zip: '80310' },
  { street: '457 Corry Trail', city: 'Kansas City', state: 'MO', zip: '64125' },
  { street: '00 Fallview Hill', city: 'Saint Paul', state: 'MN', zip: '55166' },
  {
    street: '52 Elmside Parkway',
    city: 'Cape Coral',
    state: 'FL',
    zip: '33915',
  },
  {
    street: '995 Sutherland Way',
    city: 'Rochester',
    state: 'NY',
    zip: '14652',
  },
  {
    street: '06 Arizona Place',
    city: 'Lake Charles',
    state: 'LA',
    zip: '70616',
  },
  { street: '26 3rd Point', city: 'Birmingham', state: 'AL', zip: '35205' },
  { street: '0518 Elka Hill', city: 'Lexington', state: 'KY', zip: '40586' },
  {
    street: '5 Cardinal Parkway',
    city: 'Frederick',
    state: 'MD',
    zip: '21705',
  },
  {
    street: '28653 Miller Crossing',
    city: 'Sacramento',
    state: 'CA',
    zip: '94263',
  },
  { street: '1 Pond Way', city: 'Hartford', state: 'CT', zip: '06183' },
  {
    street: '77229 Goodland Crossing',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32236',
  },
  {
    street: '0 Merrick Junction',
    city: 'Birmingham',
    state: 'AL',
    zip: '35254',
  },
  {
    street: '568 Delaware Crossing',
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84130',
  },
  {
    street: '96 Arrowood Street',
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84115',
  },
  {
    street: '7452 Karstens Pass',
    city: 'Saint Paul',
    state: 'MN',
    zip: '55188',
  },
  {
    street: '831 Farragut Terrace',
    city: 'San Luis Obispo',
    state: 'CA',
    zip: '93407',
  },
  { street: '11 Gateway Hill', city: 'Orlando', state: 'FL', zip: '32803' },
  { street: '67 Susan Trail', city: 'Huntington', state: 'WV', zip: '25721' },
  {
    street: '39486 Tennyson Avenue',
    city: 'Washington',
    state: 'DC',
    zip: '20557',
  },
  { street: '172 Morrow Road', city: 'Lexington', state: 'KY', zip: '40576' },
  { street: '285 Claremont Center', city: 'Bronx', state: 'NY', zip: '10459' },
  { street: '87 Lyons Alley', city: 'Kansas City', state: 'KS', zip: '66105' },
  {
    street: '0689 Forster Hill',
    city: 'Moreno Valley',
    state: 'CA',
    zip: '92555',
  },
  { street: '4820 8th Street', city: 'Mesquite', state: 'TX', zip: '75185' },
  { street: '67 Del Mar Point', city: 'Olympia', state: 'WA', zip: '98506' },
  { street: '3 Russell Alley', city: 'Jersey City', state: 'NJ', zip: '07310' },
  { street: '5 Mallory Court', city: 'Nashville', state: 'TN', zip: '37235' },
  { street: '8433 Judy Terrace', city: 'Tacoma', state: 'WA', zip: '98481' },
  {
    street: '1 Prairie Rose Crossing',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19146',
  },
  { street: '7111 Eastlawn Hill', city: 'Houston', state: 'TX', zip: '77025' },
  { street: '0 Bonner Road', city: 'Memphis', state: 'TN', zip: '38131' },
  { street: '43 Westend Road', city: 'Montpelier', state: 'VT', zip: '05609' },
  {
    street: '1455 Holmberg Crossing',
    city: 'Mansfield',
    state: 'OH',
    zip: '44905',
  },
  { street: '4 Lerdahl Street', city: 'Glendale', state: 'AZ', zip: '85311' },
  { street: '4 Service Center', city: 'Iowa City', state: 'IA', zip: '52245' },
  {
    street: '23484 Pierstorff Hill',
    city: 'Arlington',
    state: 'VA',
    zip: '22205',
  },
  { street: '055 Comanche Place', city: 'Houston', state: 'TX', zip: '77090' },
  {
    street: '6 Kinsman Park',
    city: 'Lawrenceville',
    state: 'GA',
    zip: '30045',
  },
  { street: '0 Dapin Place', city: 'Louisville', state: 'KY', zip: '40266' },
  {
    street: '4 Ramsey Parkway',
    city: 'Baton Rouge',
    state: 'LA',
    zip: '70883',
  },
  { street: '941 Granby Park', city: 'New Haven', state: 'CT', zip: '06533' },
  {
    street: '318 Manitowish Lane',
    city: 'Missoula',
    state: 'MT',
    zip: '59806',
  },
  { street: '85 South Avenue', city: 'Hartford', state: 'CT', zip: '06140' },
  {
    street: '2526 Evergreen Park',
    city: 'Fairfield',
    state: 'CT',
    zip: '06825',
  },
  { street: '4487 Springs Road', city: 'Beaverton', state: 'OR', zip: '97075' },
  {
    street: '153 Dahle Terrace',
    city: 'Johnson City',
    state: 'TN',
    zip: '37605',
  },
  { street: '6 Milwaukee Way', city: 'Sioux Falls', state: 'SD', zip: '57110' },
  { street: '5 Hovde Crossing', city: 'Saint Paul', state: 'MN', zip: '55127' },
];
