function timestamp() {
  // sometime in the last 30 days
  const stampy =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stampy).toISOString();
}

export const user = [
  {
    name: 'Teresa',
    lastName: 'Mycock',
    email: 'tmycock0@cyberchimps.com',
    password: 'XW0bTe4iXB',
    address: {
      street: '43 Katie Hill',
      city: 'Van Nuys',
      state: 'CA',
      zip: '91406',
    },
  },
  {
    name: 'Regan',
    lastName: 'Allain',
    email: 'rallain1@cbslocal.com',
    password: 'woyTJMU',
    address: {
      street: '84694 Arizona Drive',
      city: 'Boulder',
      state: 'CO',
      zip: '80310',
    },
  },
  {
    name: 'Vladimir',
    lastName: 'Joder',
    email: 'vjoder2@whitehouse.gov',
    password: '7iKuMQwdywa',
    address: {
      street: '457 Corry Trail',
      city: 'Kansas City',
      state: 'MO',
      zip: '64125',
    },
  },
  {
    name: 'Leighton',
    lastName: 'Epperson',
    email: 'lepperson3@yahoo.com',
    password: 'Rbi7DPo1IDX',
    address: {
      street: '00 Fallview Hill',
      city: 'Saint Paul',
      state: 'MN',
      zip: '55166',
    },
  },
  {
    name: 'Zorine',
    lastName: 'Dugget',
    email: 'zdugget4@princeton.edu',
    password: 'bGLC3stQGvEc',
    address: {
      street: '52 Elmside Parkway',
      city: 'Cape Coral',
      state: 'FL',
      zip: '33915',
    },
  },
  {
    name: 'Casar',
    lastName: 'Oswald',
    email: 'coswald5@wiley.com',
    password: '7cb7j8',
    address: {
      street: '995 Sutherland Way',
      city: 'Rochester',
      state: 'NY',
      zip: '14652',
    },
  },
  {
    name: 'Julie',
    lastName: 'Baudesson',
    email: 'jbaudesson6@google.com.au',
    password: 'WjtqeyPrTma',
    address: {
      street: '06 Arizona Place',
      city: 'Lake Charles',
      state: 'LA',
      zip: '70616',
    },
  },
  {
    name: 'Barth',
    lastName: 'Klink',
    email: 'bklink7@nature.com',
    password: '9iDOR3Xln4c',
    address: {
      street: '26 3rd Point',
      city: 'Birmingham',
      state: 'AL',
      zip: '35205',
    },
  },
  {
    name: 'Chrisse',
    lastName: 'Kettow',
    email: 'ckettow8@mail.ru',
    password: 'CsR84wmOhg8n',
    address: {
      street: '0518 Elka Hill',
      city: 'Lexington',
      state: 'KY',
      zip: '40586',
    },
  },
  {
    name: 'Franchot',
    lastName: 'Eschelle',
    email: 'feschelle9@wikispaces.com',
    password: 'b0fZ8Nqd6',
    address: {
      street: '5 Cardinal Parkway',
      city: 'Frederick',
      state: 'MD',
      zip: '21705',
    },
  },
  {
    name: 'Susy',
    lastName: 'Moorfield',
    email: 'smoorfielda@fema.gov',
    password: '04e1EenrQOUg',
    address: {
      street: '28653 Miller Crossing',
      city: 'Sacramento',
      state: 'CA',
      zip: '94263',
    },
  },
  {
    name: 'Patrick',
    lastName: 'Chafer',
    email: 'pchaferb@tinypic.com',
    password: 'dBPmjqZZ',
    address: {},
  },
  {
    name: 'Gusella',
    lastName: 'Skinner',
    email: 'gskinnerc@hud.gov',
    password: 's6TinZz3',
    address: {
      street: '77229 Goodland Crossing',
      city: 'Jacksonville',
      state: 'FL',
      zip: '32236',
    },
  },
  {
    name: 'Misha',
    lastName: 'Van Salzberger',
    email: 'mvansalzbergerd@gravatar.com',
    password: 'ifRv9wIMu',
    address: {
      street: '0 Merrick Junction',
      city: 'Birmingham',
      state: 'AL',
      zip: '35254',
    },
  },
  {
    name: 'Rona',
    lastName: 'Roz',
    email: 'rroze@huffingtonpost.com',
    password: 'nBwi6yi',
    address: {
      street: '568 Delaware Crossing',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84130',
    },
  },
  {
    name: 'Elfrida',
    lastName: 'Beagan',
    email: 'ebeaganf@shinystat.com',
    password: '5AE8MjQh1mcg',
    address: {
      street: '96 Arrowood Street',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84115',
    },
  },
  {
    name: 'Brynn',
    lastName: 'Mulholland',
    email: 'bmulhollandg@example.com',
    password: 'fL9egtCc',
    address: {
      street: '7452 Karstens Pass',
      city: 'Saint Paul',
      state: 'MN',
      zip: '55188',
    },
  },
  {
    name: 'Waldemar',
    lastName: 'Studdal',
    email: 'wstuddalh@auda.org.au',
    password: 'X3rPA8QIn',
    address: {
      street: '831 Farragut Terrace',
      city: 'San Luis Obispo',
      state: 'CA',
      zip: '93407',
    },
  },
  {
    name: 'Blinny',
    lastName: 'Discombe',
    email: 'bdiscombei@netvibes.com',
    password: 'GV8Tp9eZrp',
    address: {
      street: '39486 Tennyson Avenue',
      city: 'Washington',
      state: 'DC',
      zip: '20557',
    },
  },
  {
    name: 'Field',
    lastName: 'Hofton',
    email: 'fhoftonj@wikispaces.com',
    password: '10OFHozgN9R',
    address: {
      street: '0689 Forster Hill',
      city: 'Moreno Valley',
      state: 'CA',
      zip: '92555',
    },
  },
  {
    name: 'Brunhilda',
    lastName: 'Okker',
    email: 'bokkerk@histats.com',
    password: 'AUG6jY',
    address: {
      street: '1 Prairie Rose Crossing',
      city: 'Philadelphia',
      state: 'PA',
      zip: '19146',
    },
  },
  {
    name: 'Joya',
    lastName: 'Czaple',
    email: 'jczaplel@mozilla.org',
    password: 'x2t6a4V',
    address: {
      street: '1455 Holmberg Crossing',
      city: 'Mansfield',
      state: 'OH',
      zip: '44905',
    },
  },
  {
    name: 'Dedie',
    lastName: 'Phaup',
    email: 'dphaupm@yelp.com',
    password: 'RX3OPNK9f',
    address: {
      street: '23484 Pierstorff Hill',
      city: 'Arlington',
      state: 'VA',
      zip: '22205',
    },
  },
  {
    name: 'Dennet',
    lastName: 'Sharrem',
    email: 'dsharremn@bluehost.com',
    password: 'qydhYATwZi',
    address: {
      street: '6 Kinsman Park',
      city: 'Lawrenceville',
      state: 'GA',
      zip: '30045',
    },
  },
  {
    name: 'Garrek',
    lastName: 'Yurocjkin',
    email: 'gyurocjkino@reddit.com',
    password: 'Jy3aXCOlLz',
    address: {
      street: '4 Ramsey Parkway',
      city: 'Baton Rouge',
      state: 'LA',
      zip: '70883',
    },
  },
];

export const cuts = [
  {
    name: 'Burger',
    weight: 1,
    price: 1000,
    status: 'available',
    description: 'engage real-time web services',
    photo: {
      filename: 'burger.jpg',
      _meta: {
        asset_id: 'bec4ed6aaa5b9674e4a8517d7c13f88a',
        public_id: 'meat-friends/ckqv5sqhp00005v1i2ii1gtt2',
        format: 'jpg',
        version: 1625763814,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T17:03:34Z',
        bytes: 3133513,
        width: 3648,
        height: 5472,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625763814/meat-friends/ckqv5sqhp00005v1i2ii1gtt2.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625763814/meat-friends/ckqv5sqhp00005v1i2ii1gtt2.jpg',
      },
    },
  },
  {
    name: 'Boneless pork chop',
    weight: 0.5,
    price: 1600,
    status: 'available',
    description: 'productize out-of-the-box synergies',
    photo: {
      filename: 'pork-ribeye.jpg',
      _meta: {
        asset_id: 'e4793e7b5cf13a198483a3e49ab2ef46',
        public_id: 'meat-friends/ckqugmkz60000o31idqp02uht',
        format: 'jpg',
        version: 1625721536,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T05:18:56Z',
        bytes: 2476814,
        width: 3024,
        height: 4032,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625721536/meat-friends/ckqugmkz60000o31idqp02uht.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625721536/meat-friends/ckqugmkz60000o31idqp02uht.jpg',
      },
    },
  },
  {
    name: 'Stew pork',
    weight: 1,
    price: 1000,
    status: 'available',
    description: 'visualize synergistic e-tailers',
    photo: {
      filename: 'pork-stew.jpg',
      _meta: {
        asset_id: 'fde70cc7681a267204bb50a0354fdd22',
        public_id: 'meat-friends/pork-stew_e2uu43',
        format: 'jpg',
        version: 1625717047,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:07Z',
        bytes: 3059069,
        width: 5092,
        height: 4211,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717047/meat-friends/pork-stew_e2uu43.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717047/meat-friends/pork-stew_e2uu43.jpg',
      },
    },
  },
  {
    name: 'Salami',
    weight: 1,
    price: 2700,
    status: 'available',
    description: 'productize interactive content',
    photo: {
      filename: 'pork-stew.jpg',
      _meta: {
        asset_id: '1718df726ad082b75022d65980dca35c',
        public_id: 'meat-friends/pork-salami-2_rtoott',
        format: 'jpg',
        version: 1625717047,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:07Z',
        bytes: 5263282,
        width: 5162,
        height: 3745,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717047/meat-friends/pork-salami-2_rtoott.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717047/meat-friends/pork-salami-2_rtoott.jpg',
      },
    },
  },
  {
    name: 'Bone-in Tomahawk',
    weight: 2.4,
    price: 3800,
    status: false,
    description: 'engineer 24/7 platforms',
    photo: {
      filename: 'steak-tomahawk.jpg',
      _meta: {
        asset_id: '24d5bf121fa97527ddeb2e5617c4ccf4',
        public_id: 'meat-friends/tomahawk_bcnzvq',
        format: 'jpg',
        version: 1625717046,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:06Z',
        bytes: 1523102,
        width: 2700,
        height: 2700,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717046/meat-friends/tomahawk_bcnzvq.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717046/meat-friends/tomahawk_bcnzvq.jpg',
      },
    },
  },
  {
    name: 'Secreto',
    weight: 0.8,
    price: 1400,
    status: 'available',
    description: 'synergize dynamic technologies',
    photo: {
      filename: 'pork-thin.jpg',
      _meta: {
        asset_id: '8a271867f292059d6bdb7d27f167c225',
        public_id: 'meat-friends/pork-thin_ygtaxl',
        format: 'jpg',
        version: 1625717045,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:05Z',
        bytes: 1104595,
        width: 3844,
        height: 5064,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717045/meat-friends/pork-thin_ygtaxl.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717045/meat-friends/pork-thin_ygtaxl.jpg',
      },
    },
  },
  {
    name: 'Sirloin',
    weight: 0.6,
    price: 1400,
    status: 'available',
    description: 'benchmark robust interfaces',
    photo: {
      filename: 'pork-sirloin.jpg',
      _meta: {
        asset_id: '4299e21ee900900beb65f0a1c988be17',
        public_id: 'meat-friends/pork-sirloin_anoupk',
        format: 'jpg',
        version: 1625717045,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:05Z',
        bytes: 2062910,
        width: 6000,
        height: 4000,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717045/meat-friends/pork-sirloin_anoupk.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717045/meat-friends/pork-sirloin_anoupk.jpg',
      },
    },
  },
  {
    name: 'Pork shoulder',
    weight: 12,
    price: 5500,
    status: 'available',
    description: 'target impactful paradigms',
    photo: {
      filename: 'pork-shoulder.jpg',
      _meta: {
        asset_id: 'b939e8ccea29a5537c1eb1b8d45d6c16',
        public_id: 'meat-friends/pork-shoulder_te1p3f',
        format: 'jpg',
        version: 1625717044,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:04Z',
        bytes: 2426523,
        width: 6000,
        height: 4000,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717044/meat-friends/pork-shoulder_te1p3f.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717044/meat-friends/pork-shoulder_te1p3f.jpg',
      },
    },
  },
  {
    name: 'Basic sausage',
    weight: 0.8,
    price: 1200,
    status: 'available',
    description: 'engage value-added applications',
    photo: {
      filename: 'basic-sausage.jpg',
      _meta: {
        asset_id: '8d9f0e2c2a83578e478b2c4f2c5a9b37',
        public_id: 'meat-friends/pork-sausaage_kcu1nm',
        format: 'jpg',
        version: 1625717042,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:04:02Z',
        bytes: 2902738,
        width: 3663,
        height: 4724,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717042/meat-friends/pork-sausaage_kcu1nm.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717042/meat-friends/pork-sausaage_kcu1nm.jpg',
      },
    },
  },
  {
    name: 'Pork rib roast',
    weight: 5.5,
    price: 8500,
    status: 'available',
    description: 'facilitate integrated architectures',
    photo: {
      filename: 'pork-rib-roast.jpg',
      _meta: {
        asset_id: '98bfc2286e69fdb5ae4caeecffd585da',
        public_id: 'meat-friends/pork-rib-roast_fl6h8y',
        format: 'jpg',
        version: 1625717037,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:57Z',
        bytes: 1284793,
        width: 6000,
        height: 4000,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717037/meat-friends/pork-rib-roast_fl6h8y.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717037/meat-friends/pork-rib-roast_fl6h8y.jpg',
      },
    },
  },
  {
    name: 'Full rack of ribs',
    weight: 3.2,
    price: 2400,
    status: 'available',
    description: 'reinvent proactive niches',
    photo: {
      filename: 'spare-ribs.jpg',
      _meta: {
        asset_id: '98017902d169b98f4f2d217fa0fd1dcc',
        public_id: 'meat-friends/pork-ribs_mxpjmd',
        format: 'jpg',
        version: 1625717037,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:57Z',
        bytes: 1285546,
        width: 2538,
        height: 3384,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717037/meat-friends/pork-ribs_mxpjmd.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717037/meat-friends/pork-ribs_mxpjmd.jpg',
      },
    },
  },
  {
    name: 'City ham',
    weight: 1,
    price: 1500,
    status: 'available',
    description: 'grow synergistic bandwidth',
    photo: {
      filename: 'city-ham.jpg',
      _meta: {
        asset_id: 'd83b65357f78185a3440b3d041180e76',
        public_id: 'meat-friends/pork-ham_fpfcny',
        format: 'jpg',
        version: 1625717036,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:56Z',
        bytes: 3447317,
        width: 6878,
        height: 4588,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717036/meat-friends/pork-ham_fpfcny.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717036/meat-friends/pork-ham_fpfcny.jpg',
      },
    },
  },
  {
    name: 'Common wallaroo',
    weight: 37.5,
    price: 60,
    status: false,
    description: 'e-enable open-source vortals',
    photo: {
      filename: 'country-chop.jpg',
      _meta: {
        asset_id: '9977cdb22324dfb4ca7fbb2491078be1',
        public_id: 'meat-friends/pork-country-chop_y0pvez',
        format: 'jpg',
        version: 1625717033,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:53Z',
        bytes: 1546516,
        width: 4129,
        height: 3097,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717033/meat-friends/pork-country-chop_y0pvez.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717033/meat-friends/pork-country-chop_y0pvez.jpg',
      },
    },
  },
  {
    name: 'Pork chop',
    weight: 0.7,
    price: 1000,
    status: 'available',
    description: 'synergize extensible markets',
    photo: {
      filename: 'pork-chop.jpg',
      _meta: {
        asset_id: '6df259eaeee7bc40f4095e2c73d34543',
        public_id: 'meat-friends/pork-chop_zsvv5p',
        format: 'jpg',
        version: 1625717032,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:52Z',
        bytes: 2476814,
        width: 3024,
        height: 4032,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717032/meat-friends/pork-chop_zsvv5p.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717032/meat-friends/pork-chop_zsvv5p.jpg',
      },
    },
  },
  {
    name: 'Osso buco',
    weight: 1.2,
    price: 1250,
    status: true,
    description: 'engineer web-enabled action-items',
    photo: {
      filename: 'osso-buco.jpg',
      _meta: {
        asset_id: '4a9eb3ee96df9752dd9061ba627837c4',
        public_id: 'meat-friends/osso-buco_gtr7pm',
        format: 'jpg',
        version: 1625717029,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:49Z',
        bytes: 3310608,
        width: 3023,
        height: 3386,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717029/meat-friends/osso-buco_gtr7pm.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717029/meat-friends/osso-buco_gtr7pm.jpg',
      },
    },
  },
  {
    name: 'Bone-in pork chop',
    weight: 1.2,
    price: 1600,
    status: 'available',
    description: 'seize rich experiences',
    photo: {
      filename: 'bone-pork-chop.jpg',
      _meta: {
        asset_id: 'd033d55e7f1a12fcd1c7abb3e1786723',
        public_id: 'meat-friends/pork-bone-ribeye_pgvv4m',
        format: 'jpg',
        version: 1625717028,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:48Z',
        bytes: 627932,
        width: 3264,
        height: 1836,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717028/meat-friends/pork-bone-ribeye_pgvv4m.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717028/meat-friends/pork-bone-ribeye_pgvv4m.jpg',
      },
    },
  },
  {
    name: 'Bacon',
    weight: 1,
    price: 12,
    status: true,
    description: 'seize B2B platforms',
    photo: {
      filename: 'bacon.jpg',
      _meta: {
        asset_id: 'a52b9248d26d1893e6522530ccc7d58a',
        public_id: 'meat-friends/pork-bacon_v6tise',
        format: 'jpg',
        version: 1625717027,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:47Z',
        bytes: 2645940,
        width: 3024,
        height: 4032,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717027/meat-friends/pork-bacon_v6tise.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717027/meat-friends/pork-bacon_v6tise.jpg',
      },
    },
  },
  {
    name: 'Rolled pork belly roast',
    weight: 2.5,
    price: 3000,
    status: 'available',
    description: 'redefine transparent networks',
    photo: {
      filename: 'rolled-pork-belly.jpg',
      _meta: {
        asset_id: '5d66e55a98610d734d82a93d38630ca9',
        public_id: 'meat-friends/pork-belly-rolled_zprznl',
        format: 'jpg',
        version: 1625717025,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:45Z',
        bytes: 2084662,
        width: 2832,
        height: 4240,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717025/meat-friends/pork-belly-rolled_zprznl.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717025/meat-friends/pork-belly-rolled_zprznl.jpg',
      },
    },
  },
  {
    name: 'Delmonico',
    weight: 1.2,
    price: 1800,
    status: 'available',
    description: 'grow user-centric interfaces',
    photo: {
      filename: 'delmonico.jpg',
      _meta: {
        asset_id: '15a7d6a1b3db8520d40fd937052c0ee8',
        public_id: 'meat-friends/beef-delmonico_n62fmq',
        format: 'jpg',
        version: 1625717021,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:41Z',
        bytes: 9362074,
        width: 6889,
        height: 4593,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717021/meat-friends/beef-delmonico_n62fmq.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717021/meat-friends/beef-delmonico_n62fmq.jpg',
      },
    },
  },
  {
    name: 'Short rib',
    weight: 1.2,
    price: 1600,
    status: 'avialable',
    description: 'utilize mission-critical channels',
    photo: {
      filename: 'short-rib.jpg',
      _meta: {
        asset_id: '571b2e13e1db1ba62900cac7daa789b7',
        public_id: 'meat-friends/beef-short-rib_ssctus',
        format: 'jpg',
        version: 1625717019,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:39Z',
        bytes: 5822492,
        width: 3840,
        height: 5760,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717019/meat-friends/beef-short-rib_ssctus.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717019/meat-friends/beef-short-rib_ssctus.jpg',
      },
    },
  },
  {
    name: 'Eye of round',
    weight: 3.2,
    price: 2400,
    status: 'available',
    description: 'leverage vertical e-services',
    photo: {
      filename: 'eye-of-round.jpg',
      _meta: {
        asset_id: '9f597bd75e4cb838093a0eaaa57dde03',
        public_id: 'meat-friends/beef-round_kgt2za',
        format: 'jpg',
        version: 1625717019,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:39Z',
        bytes: 6736031,
        width: 4000,
        height: 6000,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717019/meat-friends/beef-round_kgt2za.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717019/meat-friends/beef-round_kgt2za.jpg',
      },
    },
  },
  {
    name: 'Chicken breast',
    weight: 0.6,
    price: 800,
    status: 'available',
    description: 'extend efficient partnerships',
    photo: {
      filename: 'whole-chicken.jpg',
      _meta: {
        asset_id: 'ab2a56a9fcd220034c352b6c1826f78a',
        public_id: 'meat-friends/chicken_rpcf65',
        format: 'jpg',
        version: 1625717018,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:38Z',
        bytes: 1257871,
        width: 3410,
        height: 5115,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717018/meat-friends/chicken_rpcf65.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717018/meat-friends/chicken_rpcf65.jpg',
      },
    },
  },
  {
    name: 'Strip steak',
    weight: 2.4,
    price: 2000,
    status: 'available',
    description: 'drive dynamic users',
    photo: {
      filename: 'stripe-steak.jpg',
      _meta: {
        asset_id: '61e31950819d41d4d920a440e2ef8bf6',
        public_id: 'meat-friends/beef-strip_jx0ggn',
        format: 'jpg',
        version: 1625717018,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:38Z',
        bytes: 3590524,
        width: 4896,
        height: 3264,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717018/meat-friends/beef-strip_jx0ggn.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717018/meat-friends/beef-strip_jx0ggn.jpg',
      },
    },
  },
  {
    name: 'Bone in ribeye',
    weight: 1.5,
    price: 2500,
    status: 'available',
    description: 'visualize cross-platform methodologies',
    photo: {
      filename: 'bone-ribeye.jpg',
      _meta: {
        asset_id: '92a1fdaf279fd79e20bcdcf5ac5202a7',
        public_id: 'meat-friends/beef-bone-ribeye_x4orqp',
        format: 'jpg',
        version: 1625717016,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:36Z',
        bytes: 7331331,
        width: 3966,
        height: 5949,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717016/meat-friends/beef-bone-ribeye_x4orqp.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717016/meat-friends/beef-bone-ribeye_x4orqp.jpg',
      },
    },
  },
  {
    name: 'Whole Chicken',
    weight: 1.5,
    price: 1500,
    status: false,
    description: 'evolve bricks-and-clicks models',
    photo: {
      filename: 'whole-chicken.jpb',
      _meta: {
        asset_id: '0a6df9622729fc5147913c98a41e776e',
        public_id: 'meat-friends/chicken-whole_xfigsw',
        format: 'jpg',
        version: 1625717013,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:33Z',
        bytes: 2398549,
        width: 2781,
        height: 4171,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717013/meat-friends/chicken-whole_xfigsw.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717013/meat-friends/chicken-whole_xfigsw.jpg',
      },
    },
  },
  {
    name: 'Porterhouse',
    weight: 1.5,
    price: 2600,
    status: true,
    description: 'enhance open-source niches',
    photo: {
      filename: 'porterhouse.jpg',
      _meta: {
        asset_id: '49eb36793e68d69e7b05c39cdc2db8db',
        public_id: 'meat-friends/beef-porthouse_nnbksm',
        format: 'jpg',
        version: 1625717007,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:27Z',
        bytes: 3020534,
        width: 3744,
        height: 5616,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717007/meat-friends/beef-porthouse_nnbksm.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717007/meat-friends/beef-porthouse_nnbksm.jpg',
      },
    },
  },
  {
    name: 'Beef Burger Patties',
    weight: 1.2,
    price: 1400,
    status: true,
    description: 'brand holistic bandwidth',
    photo: {
      filename: 'beef-burger.jpg',
      _meta: {
        asset_id: '7b2eb70bd8967d5c231ed5e78c61e7fa',
        public_id: 'meat-friends/beef-burger_t56jfp',
        format: 'jpg',
        version: 1625717006,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:26Z',
        bytes: 3133513,
        width: 3648,
        height: 5472,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717006/meat-friends/beef-burger_t56jfp.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717006/meat-friends/beef-burger_t56jfp.jpg',
      },
    },
  },
  {
    name: 'Bistro steak',
    weight: 1,
    price: 1400,
    status: false,
    description: 'extend real-time e-business',
    photo: {
      filename: 'bistro-steak.jpg',
      _meta: {
        asset_id: '7b9f2dbc7f173889889d08bab91ad708',
        public_id: 'meat-friends/beef-bistro_sdmfn1',
        format: 'jpg',
        version: 1625717005,
        resource_type: 'image',
        type: 'upload',
        created_at: '2021-07-08T04:03:25Z',
        bytes: 2291778,
        width: 4986,
        height: 3324,
        url: 'http://res.cloudinary.com/meat-friends/image/upload/v1625717005/meat-friends/beef-bistro_sdmfn1.jpg',
        secure_url:
          'https://res.cloudinary.com/meat-friends/image/upload/v1625717005/meat-friends/beef-bistro_sdmfn1.jpg',
      },
    },
  },
];
