export const user = [
  {
    firstName: 'Teresa',
    lastName: 'Mycock',
    email: 'tmycock0@cyberchimps.com',
    password: 'XW0bTe4iXB',
  },
  {
    firstName: 'Regan',
    lastName: 'Allain',
    email: 'rallain1@cbslocal.com',
    password: 'woyTJMU',
  },
  {
    firstName: 'Vladimir',
    lastName: 'Joder',
    email: 'vjoder2@whitehouse.gov',
    password: '7iKuMQwdywa',
  },
  {
    firstName: 'Leighton',
    lastName: 'Epperson',
    email: 'lepperson3@yahoo.com',
    password: 'Rbi7DPo1IDX',
  },
  {
    firstName: 'Zorine',
    lastName: 'Dugget',
    email: 'zdugget4@princeton.edu',
    password: 'bGLC3stQGvEc',
  },
  {
    firstName: 'Casar',
    lastName: 'Oswald',
    email: 'coswald5@wiley.com',
    password: '7cb7j8',
  },
  {
    firstName: 'Julie',
    lastName: 'Baudesson',
    email: 'jbaudesson6@google.com.au',
    password: 'WjtqeyPrTma',
  },
  {
    firstName: 'Barth',
    lastName: 'Klink',
    email: 'bklink7@nature.com',
    password: '9iDOR3Xln4c',
  },
  {
    firstName: 'Chrisse',
    lastName: 'Kettow',
    email: 'ckettow8@mail.ru',
    password: 'CsR84wmOhg8n',
  },
  {
    firstName: 'Franchot',
    lastName: 'Eschelle',
    email: 'feschelle9@wikispaces.com',
    password: 'b0fZ8Nqd6',
  },
  {
    firstName: 'Susy',
    lastName: 'Moorfield',
    email: 'smoorfielda@fema.gov',
    password: '04e1EenrQOUg',
  },
  {
    firstName: 'Patrick',
    lastName: 'Chafer',
    email: 'pchaferb@tinypic.com',
    password: 'dBPmjqZZ',
  },
  {
    firstName: 'Gusella',
    lastName: 'Skinner',
    email: 'gskinnerc@hud.gov',
    password: 's6TinZz3',
  },
  {
    firstName: 'Misha',
    lastName: 'Van Salzberger',
    email: 'mvansalzbergerd@gravatar.com',
    password: 'ifRv9wIMu',
  },
  {
    firstName: 'Rona',
    lastName: 'Roz',
    email: 'rroze@huffingtonpost.com',
    password: 'nBwi6yi',
  },
  {
    firstName: 'Elfrida',
    lastName: 'Beagan',
    email: 'ebeaganf@shinystat.com',
    password: '5AE8MjQh1mcg',
  },
  {
    firstName: 'Brynn',
    lastName: 'Mulholland',
    email: 'bmulhollandg@example.com',
    password: 'fL9egtCc',
  },
  {
    firstName: 'Waldemar',
    lastName: 'Studdal',
    email: 'wstuddalh@auda.org.au',
    password: 'X3rPA8QIn',
  },
  {
    firstName: 'Blinny',
    lastName: 'Discombe',
    email: 'bdiscombei@netvibes.com',
    password: 'GV8Tp9eZrp',
  },
  {
    firstName: 'Field',
    lastName: 'Hofton',
    email: 'fhoftonj@wikispaces.com',
    password: '10OFHozgN9R',
  },
  {
    firstName: 'Brunhilda',
    lastName: 'Okker',
    email: 'bokkerk@histats.com',
    password: 'AUG6jY',
  },
  {
    firstName: 'Joya',
    lastName: 'Czaple',
    email: 'jczaplel@mozilla.org',
    password: 'x2t6a4V',
  },
  {
    firstName: 'Dedie',
    lastName: 'Phaup',
    email: 'dphaupm@yelp.com',
    password: 'RX3OPNK9f',
  },
  {
    firstName: 'Dennet',
    lastName: 'Sharrem',
    email: 'dsharremn@bluehost.com',
    password: 'qydhYATwZi',
  },
  {
    firstName: 'Garrek',
    lastName: 'Yurocjkin',
    email: 'gyurocjkino@reddit.com',
    password: 'Jy3aXCOlLz',
  },
];
